### ISSUE TITLE
Rewrite to Kotlin

### ISSUE THREAD

**Issue by y9san9** [ktorio/ktor-cli#28]
Of course title is kinda joke, but the serious question is why have you chosen Go instead or trying to adapt Kotlin/Native for example? And reporting issues with it on the way, that will help Kotlin to become better.

**Comment by Stexxe** [comment]
The main two reasons we've chosen Go over Kotlin/Native are cross-compilation and the vast standard library, which includes everything (tar, gzip, zip, HTTP client, JSON support) required for building the tool.
The other reasons are:
- Statically linked executables (Ktor requires `libcurl-devel` on the native targets)
- Compilation requires much less RAM
- Faster compilation speed

**Comment by IRus** [comment]
Would it be great to dog-food Kotlin/Native? Or it's rather target to v2, after achieving project goals?

**Comment by Stexxe** [comment]
It would be great to dog-food Kotlin/Native, but that's not gonna happen because of the above reasons.

**Comment by y9san9** [comment]
Couldn't the issues be fixed? Will Kotlin/Native never be great for such command line utils?

**Comment by Stexxe** [comment]
> Couldn't the issues be fixed?

I guess, they could be fixed at some point.

> Will Kotlin/Native never be great for such command line utils?

Maybe, I don't know.

**Comment by SPC-code** [comment]
@Stexxe 

> * Statically linked executables (Ktor requires `libcurl-devel` on the native targets)

Ktor has CIO client that does not require external dependencies.

> * Compilation requires much less RAM
> * Faster compilation speed

Indeed, LLVM is hungrier than Go compiler, but it is a very small inconvenience and completely irrelevant for the end user.

All in all, it seems that reputational losses for kotlin ecosystem far outweigh the convenience of writing it in Go. And I agree with @IRus and @y9san9, dogfooding makes much more sense. There are a lot of requests for more convenient Kotlin/Native CLI experience. It would make sense to enhance it.

**Comment by Stexxe** [comment]
The CIO engine on the native targets doesn't support HTTPS.

**Comment by SPC-code** [comment]
Indeed, but maybe it is better to add cryptography to kotlin client. @whyoleg showed [here](https://github.com/whyoleg/cryptography-kotlin) that it is quite possible to do multiplatform cryptography.

**Comment by y9vad9** [comment]
totally agree with @y9san9 in this matter, Ktor as well as Kotlin, if positioning themselves multiplatform and with possible target to native targets, makes it look bad for public audience. Looks like some kind of joke and thing to be easily laugh at 🤷‍♂️

**Comment by e5l** [comment]
Hey, folks! Thanks for the report! We tried it in the first iteration, but it didn't work well—we can't build a distribution that works well on all machines. 

The issue with linking and dependency management is difficult to fix quickly, but we can't be blocked by it anymore. We will make another attempt when it is resolved!
