### ISSUE TITLE
`brew install` not working on M1 Mac (`arm64`)

### ISSUE THREAD

**Issue by sureshg** [ktorio/ktor-cli#8]
### Env
```bash
ProductName:	macOS Monterey
ProductVersion:	12.5
M1 (Arm64)
```

`brew install` fails in invalid CPU arch error.

### Error
```bash
$ brew tap ktorio/ktor
...
$ brew install --build-from-source ktor                                                                                                                                                   
ktor: The x86_64 architecture is required for this software.
Error: ktor: An unsatisfied requirement failed this build.
```

**Comment by Stexxe** [comment]
Please install [rosetta](https://support.apple.com/en-us/HT211861) to be able to install and run Ktor utility.
```bash
softwareupdate --install-rosetta
```

**Comment by utamori** [comment]
@Stexxe 
Thanks for developing the new version.
Will v0.2.0 also be available in homebrew format?

https://github.com/ktorio/homebrew-ktor

**Comment by Stexxe** [comment]
@utamori, yes, we will soon add the formula to Homebrew.

**Comment by Stexxe** [comment]
You can now install the tool via [Homebrew](https://formulae.brew.sh/formula/ktor). The readme will be updated by [this PR](https://github.com/ktorio/ktor-cli/pull/29).
